### ISSUE TITLE
Websocket connection to failed: There was a bad response from the server.

### ISSUE THREAD

**Issue by adi6409** [ijsKoud/PaperPlane#215] opened 2022-12-22 09:18 UTC
Hi, i am trying to deploy paperplane to my raspberry pi 4, and no matter what i try when i access the web panel it just gets stuck on 3 bouncing dots or nothing happens after i press login. in the javascript console it says this:
[Error] WebSocket connection to 'wss://hypere.app/websocket' failed: There was a bad response from the server.
[Log] ws connection closed – 1006 (_app-bc7ad50d2ae2a128.js, line 1)

i tried via docker, same thing.
is there something i'm doing wrong?
thanks!

**Comment by ijsKoud** [comment] 2022-12-22 09:31
Can you show me the PaperPlane logs (/logs/*.log file), and if possible the startup arguments for Docker

**Comment by adi6409** [comment] 2022-12-22 10:26
sure, im trying to run it via yarn, as for me port 3000 is occupied by mastodon. right now i shut mastodon down while im trying to run paperplane as it keeps defaulting to port 3000 instead of 7173.
[1671700526608-v3.1.5-paperplane.log](https://github.com/ijsKoud/PaperPlane/files/10286099/1671700526608-v3.1.5-paperplane.log)

**Comment by adi6409** [comment] 2022-12-22 10:33
i tried with different versions of paperplane as well.

**Comment by ijsKoud** [comment] 2022-12-22 11:22
weird, can you try running it via Docker using the default 3000 port. You can use the `--port local:docker` flag to change the outgoing port for connections (in this case for you: `--port 7173:3000`)

**Comment by adi6409** [comment] 2022-12-22 11:27
so using the command:
docker run --name=paperplane -d -v ~/paperplane:/paperplane/data -p 7173:3000 ghcr.io/ijskoud/paperplane:v3
it says WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Comment by ijsKoud** [comment] 2022-12-22 11:43
Oops, that's my fault for not adding a platform list. I am trying to build a dev instance now, it should be available in a couple of minutes.

**Comment by adi6409** [comment] 2022-12-22 11:44
thanks! please let me know when it's available.

**Comment by adi6409** [comment] 2022-12-22 12:01
Alright! take your time! i'm now trying the dev package anyway. i know it won't work, but ill try using that docker image that lets you run anything on arm64

**Comment by ijsKoud** [comment] 2022-12-22 13:23
should be ready in a couple of minutes (hopefully)

**Comment by ijsKoud** [comment] 2022-12-22 13:45
as far as I know, once [this build](https://github.com/ijsKoud/PaperPlane/actions/runs/3758277804/jobs/6386420008) is complete you can download the dev version using: `ghcr.io/ijskoud/paperplane:dev`. If it failed, than I will have to look at it tomorrow.

**Comment by ijsKoud** [comment] 2022-12-22 14:51
You can download it now!

**Comment by adi6409** [comment] 2022-12-22 15:00
Thanks, testing.

**Comment by adi6409** [comment] 2022-12-22 15:04
<img width="1680" alt="Screenshot 2022-12-22 at 17 04 05" src="https://user-images.githubusercontent.com/40761968/209162828-79261a7a-e1e4-4169-a2ae-f2f2a822cb6c.png">
<img width="1680" alt="Screenshot 2022-12-22 at 17 04 13" src="https://user-images.githubusercontent.com/40761968/209162850-738b0f1d-0229-47a8-999c-bd2e0aca9c75.png">
:/

shows 502 error, also showed that while trying with the docker amd64 image using the binfmt image.

**Comment by adi6409** [comment] 2022-12-22 15:07
important to say i'm using the nginx config, while trying to access paperplane from the pi itself it just loops refreshing between err socket not connected and err empty response.

**Comment by adi6409** [comment] 2022-12-22 15:31
changed port to 3000 in both command and .env. now it has the same 3 dots issue. attaching video.

https://user-images.githubusercontent.com/40761968/209168072-3ec14794-c79f-4983-a01c-9f27f1d8835a.mov

**Comment by ijsKoud** [comment] 2022-12-22 17:00
Can you change the internal PaperPlane port (the one in Docker) to 3000?

**Comment by adi6409** [comment] 2022-12-22 17:40
Yup, changed and it now has the same original issue with the websocket error

**Comment by ijsKoud** [comment] 2022-12-22 19:44
Oh F, can you show me the NGINX config?

**Comment by adi6409** [comment] 2022-12-22 20:11
NGINX is not the problem, tried without nginx directly using port 3000 and it still had the dots issue.

**Comment by ijsKoud** [comment] 2022-12-22 23:21
Ah alright

**Comment by ijsKoud** [comment] 2022-12-22 23:23
It could be an issue with your firewall, if you are using your own home network than your firewalls might block a ws connection.

**Comment by adi6409** [comment] 2022-12-23 06:42
yeah i actually don't have a firewall, and i tried a few different networks and none work. 
also just tried on my M2 macbook pro with the new docker image and it has the same issue!
probably forgot to mention it also had the same issue while running paperplane from the source using yarn.
<img width="1680" alt="Screenshot 2022-12-23 at 8 41 10" src="https://user-images.githubusercontent.com/40761968/209285435-57ee2047-0617-4021-a6cf-e60594531a13.png">

**Comment by adi6409** [comment] 2022-12-23 07:10
interestingly enough, when i run using yarn dev i get this error on the dashboard and index page:
<img width="1680" alt="Screenshot 2022-12-23 at 9 10 28" src="https://user-images.githubusercontent.com/40761968/209289305-b7211706-8a26-4617-967f-05a68ded40c8.png">

**Comment by ijsKoud** [comment] 2022-12-23 07:12
that is a React error and shouldn't break the websocket stuff.

**Comment by adi6409** [comment] 2022-12-23 07:13
yes, but the websocket works on yarn dev. when i run using yarn dev the websocket works and if i go to /login and type username and passwords i get the green notification it redirects me to the dashboard and shows this.

**Comment by ijsKoud** [comment] 2022-12-23 07:13
oh that's interesting

**Comment by adi6409** [comment] 2022-12-23 07:18
yup

btw i went to the useAuth.tsx file and swapped the if and the return, so instead of 
	const getProtocol = () => {
		const env = process.env.NEXT_PUBLIC_SECURE;
		if (env && env === "false") return "ws://";

		return "wss://";
	};
	
	i put:
		const getProtocol = () => {
		const env = process.env.NEXT_PUBLIC_SECURE;
		if (env && env === "true") return "wss://";

		return "ws://";
	};

**Comment by ijsKoud** [comment] 2022-12-23 07:19
Ah you beat me too it. I was about to tell you that I found the issue yea

**Comment by adi6409** [comment] 2022-12-23 07:20
yeah, but even after the change and running yarn build it has the same issue.

**Comment by ijsKoud** [comment] 2022-12-23 07:21
It is working as expected, it only didn't work for you in the local environment because you didn't set the NEXT_PUBLIC_SECURE var in `.env`

**Comment by adi6409** [comment] 2022-12-23 07:23
hmmmmm

in the guide it said SECURE

might be a good idea to attach my .env here, without the generated key:

NAME_TYPE="name"
PORT=3000
SECURE=false

(it has port 3000 only for the testing and then i'll switch to 7173)

ill change to NEXT_PUBLIC_SECURE, run yarn build and ill let ya know.

**Comment by ijsKoud** [comment] 2022-12-23 07:25
just saw that for some reason the SECURE variable does not really want to work so I will have to find a fix for that.

**Comment by adi6409** [comment] 2022-12-23 07:26
nope didn't work for me ;/

i have two .env files because i dont know which one works, i have one in . and one in ./data. i changed both to include NEXT_PUBLIC_SECURE=false but still error 1006 after running yarn build and yarn start

**Comment by ijsKoud** [comment] 2022-12-23 07:41
Yea it has something to do with a env set issue. I am working on a fix

**Comment by ijsKoud** [comment] 2022-12-23 07:45
A fix should be ready now, if you run `git pull` and start the dev or prod version everything should work again.

**Comment by adi6409** [comment] 2022-12-23 07:46
i'll test now, thanks

**Comment by adi6409** [comment] 2022-12-23 07:50
now it shows this.
<img width="1680" alt="Screenshot 2022-12-23 at 9 49 56" src="https://user-images.githubusercontent.com/40761968/209295242-3c377893-8e38-4ccc-844d-fcde7480a25d.png">

**Comment by ijsKoud** [comment] 2022-12-23 07:50
can you show me the paperplane logs pls

**Comment by adi6409** [comment] 2022-12-23 07:51
<img width="1680" alt="Screenshot 2022-12-23 at 9 51 36" src="https://user-images.githubusercontent.com/40761968/209295457-589363d4-fd6b-465f-8733-9eca8daeb5be.png">

**Comment by adi6409** [comment] 2022-12-23 07:51
oh shit im stupid its a database problem

**Comment by ijsKoud** [comment] 2022-12-23 07:52
you data.db file is missing

**Comment by adi6409** [comment] 2022-12-23 07:52
forgot to create the data folder

**Comment by ijsKoud** [comment] 2022-12-23 07:53
you can run `yarn prisma db push` to fix it.

**Comment by adi6409** [comment] 2022-12-23 07:54
ended up copying the db file from the other fresh install to data. back to square one :/
<img width="1680" alt="Screenshot 2022-12-23 at 9 53 37" src="https://user-images.githubusercontent.com/40761968/209295750-d0ed82ce-f358-44f7-836b-3996621b48c6.png">

**Comment by adi6409** [comment] 2022-12-23 07:56
only now it doesnt even connect to websocket while using yarn dev as well

**Comment by ijsKoud** [comment] 2022-12-23 08:07
can you clear your Chrome/FireFox cache, your dist folder and your .next folder. Probably cached javascript being annoying

**Comment by ijsKoud** [comment] 2022-12-23 08:08
I also published a Docker Dev version, you can try that one as well if you like.

**Comment by adi6409** [comment] 2022-12-23 08:12
tried deleting the folders and clearing cache, still nothing with yarn start. with yarn dev, however, it worked! i logged into the dashboard. what should i try next?

**Comment by ijsKoud** [comment] 2022-12-23 08:13
Oh then you probably didnt run yarn build did you?

**Comment by adi6409** [comment] 2022-12-23 08:14
i did

**Comment by adi6409** [comment] 2022-12-23 08:15
also, forgot to mention after everything works i'll upload it to my raspberry pi which uses https.

**Comment by ijsKoud** [comment] 2022-12-23 08:19
> i did

hmmmm

**Comment by ijsKoud** [comment] 2022-12-23 08:22
oh wow correct, weird. Worked for me the first time but now it seems to stop again as well

**Comment by ijsKoud** [comment] 2022-12-23 08:24
oh oops. Just realized that you are supposed to run `node .` and not `yarn start`.

**Comment by adi6409** [comment] 2022-12-23 08:24
after yarn build?

**Comment by adi6409** [comment] 2022-12-23 08:25
yup that worked.  ill now try with https

**Comment by ijsKoud** [comment] 2022-12-23 08:26
yep, if you run `node .` now it starts the Application correctly. `yarn start` only starts the front-end (the dashboard) and not the server

**Comment by ijsKoud** [comment] 2022-12-23 08:26
> yup that worked. ill now try with https

Awesome!

**Comment by adi6409** [comment] 2022-12-23 08:31
whoops, nginx gives error 502. attac
hing config, paperplane says listening on port 7173
[default.txt](https://github.com/ijsKoud/PaperPlane/files/10293591/default.txt)

**Comment by ijsKoud** [comment] 2022-12-23 08:36
Why do you have a two servers for the same app???

**Comment by adi6409** [comment] 2022-12-23 08:38
i just copied the mastodon config and edited it to include the location / tags. i think one is for http and one is for https.

**Comment by adi6409** [comment] 2022-12-23 08:38
i dont, i performed the tests on my macbook and i am trying to deploy to the raspberry pi.

**Comment by ijsKoud** [comment] 2022-12-23 08:40
afaik you only need one unless, the 80 if ssl is handled by for example Cloudflare and 443 if its handled on the server by for example LetsEncrypt

**Comment by adi6409** [comment] 2022-12-23 08:42
idk, i used certbot to generate the ssl certificate, but when i tried deploying paperplane a few days ago i managed to get to the non-working paperplane from the domain with the exact same config.

**Comment by adi6409** [comment] 2022-12-23 08:44
hmm, seems to be working now, but the paperplane logo is missing.

**Comment by ijsKoud** [comment] 2022-12-23 08:44
Yea I noticed that aswell, but I believe that is a browser issue or something cuz the file is still accessible and can be found in the public folder

**Comment by adi6409** [comment] 2022-12-23 08:45
and the websocket fails to connect on https. same error 1006.

**Comment by adi6409** [comment] 2022-12-23 08:47
wait wtf i dont have paperplane running how is it working

**Comment by ijsKoud** [comment] 2022-12-23 08:50
> wait wtf i dont have paperplane running how is it working

probably an incorrectly stopped application still running in the bg

**Comment by adi6409** [comment] 2022-12-23 08:51
yeah i am trying to run it with pm2 but it is freaking out. i just rebooted the pi, now waiting for it to boot up and ill keep you updated.

**Comment by adi6409** [comment] 2022-12-23 08:55
same ws error, probably because pm2 command is wrong. ill try using docker

**Comment by adi6409** [comment] 2022-12-23 09:05
with docker it just has the connection refused issue, even while trying to access from localhost.

**Comment by ijsKoud** [comment] 2022-12-23 09:05
the port is not set correctly in that case

**Comment by adi6409** [comment] 2022-12-23 09:10
nope, lsof -i :7173 says docker, paperplane logs say 7173, web browser says connection refused or 502 if accessed from nginx

**Comment by ijsKoud** [comment] 2022-12-23 09:12
7173:7173 or just :7173, if it's the last one than the ports aren't setup correctly

**Comment by adi6409** [comment] 2022-12-23 09:13
i ran the command sudo docker run --name=paperplane -d -v ~/paperplane:/paperplane/data -p 7173:3000 ghcr.io/ijskoud/paperplane:dev

**Comment by ijsKoud** [comment] 2022-12-23 09:15
if everything worked on your local devices but doesnt on your Rasp Pi then you NGINX config or something like that must be incorrectly configured.

**Comment by adi6409** [comment] 2022-12-23 09:16
on my macbook i only tried the yarn method, without docker. should i try running docker run --name=paperplane -d -v ~/paperplane:/paperplane/data -p 7173:7173 ghcr.io/ijskoud/paperplane:dev on the pi? notice i changed 7173:3000 to 7173:7173

**Comment by ijsKoud** [comment] 2022-12-23 09:17
that doesn't work unless you change the internal PaperPlane port from 3000 to 7173 too. And if you did that, you will prob get the same output

**Comment by adi6409** [comment] 2022-12-23 09:18
so what should i do?

**Comment by ijsKoud** [comment] 2022-12-23 09:20
everything outside of PaperPlane while running paperplane is out of my workfield, I believe the ws issue is fixed now (unless you tell me otherwise) so either fix your NGINX if that is incorrectly configured or run it on another platform

**Comment by adi6409** [comment] 2022-12-23 09:20
ran docker run --name=paperplane -d -v ~/paperplane:/paperplane/data -p 7173:7173 ghcr.io/ijskoud/paperplane:dev, have the same issue with the websocket not working on https.

**Comment by ijsKoud** [comment] 2022-12-23 09:32
I cannot reproduce the https issue atm

**Comment by ijsKoud** [comment] 2022-12-23 09:35
I am going to close this issue now, feel free to continue this thread if you need more support but the PaperPlane issue is resolved now.

**Comment by adi6409** [comment] 2022-12-23 09:36
Alright, Thank you very much for the support!

**Closed by ijsKoud** 2022-12-23 09:35 UTC
Labels: Bug 🐛, Question ❓
